### ISSUE TITLE
Running a year long SCM 

### ISSUE THREAD

**Issue by lpassarella** [E3SM-Project/scmlib#1]
I am trying to run a SCM on the E3SMv2 with the iop file:SGP_continuous_iopfile_4scam.nc for a year. However, when I go to change the walltime, I am unable to request more than 30 minutes to run my model.

Is there a more efficient way to get a longer run on the SCM? Thank you!

**Comment by whannah1** [comment]
@lpassarella what machine are you on?
I could be wrong about this, but I don't think we ever implemented the ability to restart an SCM run, so you might need to find a machine that doesn't have a batch system. I've done long SCM runs on a local machine before, so the 30 min time limit you are seeing shouldn't be anything inherent to the model itself.

**Comment by rljacob** [comment]
If your job is being routed to a debug queue, that could force a 30 minute limit.

**Comment by lpassarella** [comment]
I am using Cori, it was being routed to debug so I fixed that. Thank you for your help!
