### ISSUE TITLE
SCM scripts no longer work out of the box on version 2.0

### ISSUE THREAD

**Issue by quantheory** [E3SM-Project/scmlib#2]
Because of commit 33d2b72, which allowed the scripts to work on the E3SM master again, they no longer work directly on v2. This is easy to work around, but could be an issue in the future.

I'm not sure whether the best fix is to port the compset change to the E3SM maint-2.0 branch (so that any new v2 checkouts/tags will have the name change), or to change the scmlib scripts so that e3sm_version has more options (e.g. besides "v1" and "v2", also letting it be set to "master" or "development" or something, and have that affect the compset name used).

**Comment by quantheory** [comment]
@bogensch

**Comment by bogensch** [comment]
Thanks @quantheory for bringing this to my attention.  I will come up with the solution to the E3SM SCM scripts soon and close this issue once it has been addressed.

**Comment by bogensch** [comment]
Issue has been addressed and scripts now have a "v1", "v2", or "master" option.
